name: main

on:
  push:
    branches:
      - main
  # Chạy tay từ Github
  workflow_dispatch:
  # Chạy hàng ngày: 00:00 UTC
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.14.2
      - run: npm ci
      - name: Get new quote
        run: npm start
      - name: Update README
        run: |
          git config --global user.email "trieuvanbd123@gmail.com"
          git config --global user.name "yuran1811"
          git add .
          git commit -m "Update README" || echo "No changes to commit"
          git push
